### ISSUE TITLE
Q: how does one extract the predictions and assign it to a vector in a DT

### ISSUE THREAD

**Issue by zeltak** [vonjd/OneR#2]
Hi thx for the great package

i have a basic question. 
How does one extract the predictions and assign it to a vector in a DT?

for example if i predict using
`prediction <- predict(model, BASH)`
the result is an object that looks like this

```
str(prediction)
 Named chr [1:97] "(51,57.1]" "(63.2,69.3]" "(51,57.1]" "(63.2,69.3]" "(63.2,69.3]" "(63.2,69.3]" "(63.2,69.3]" ...
 - attr(*, "names")= chr [1:97] "(235,469]" "(0.279,235]" "(235,469]" "(0.279,235]" ...
```

how does one extract just the predictions to a column/vector in a DT ? i would like to check the R2 to estimate the CV quality of the prediction

thx so much

Z

**Comment by vonjd** [comment]
Thank you for using the OneR package and your question!

I don't know whether I understand your question correctly, but the result you get is a character vector and you can use the standard R methods for adding that to other data structures (like cbind...).

When you want to check the quality of the prediction have you considered the eval_model function of the package?

Perhaps you could post your code with some sample data so that I can understand your problem better.

Thank you and till then

best
h

**Comment by zeltak** [comment]
thx for the quick response. this answers my question 

best

Z
