### ISSUE TITLE
can `optbin()` package provides WOE results of the bins? 

### ISSUE THREAD

**Issue by Leo-Lee15** [vonjd/OneR#6]
Thanks for the awesome package! 

Lately, I use your package for some analysis. I think it would be better if the `OneR` package provides more information on the bins. For example, the `woebin()` function in  [`scorecard`](https://mirrors.tuna.tsinghua.edu.cn/CRAN/web/packages/scorecard/index.html) package provides the following information.
```r
x <- iris[iris$Species %in% c("setosa", "virginica"), ]
x$Species <- ifelse(x$Species == "setosa", 1L, 0L)
scorecard::woebin(dt = x, y = "Species", x = "Sepal.Length")
```
```r
$`Sepal.Length`
       variable        bin count count_distr good bad    badprob       woe   bin_iv total_iv breaks is_special_values
1: Sepal.Length   [-Inf,5)    21        0.21    1  20 0.95238095  2.995732 1.138378 6.124554      5             FALSE
2: Sepal.Length    [5,5.8)    31        0.31    2  29 0.93548387  2.674149 1.444040 6.124554    5.8             FALSE
3: Sepal.Length [5.8, Inf)    48        0.48   47   1 0.02083333 -3.850148 3.542136 6.124554    Inf             FALSE
```
Would you mind considering provides these additional information in the `optbin()` function or other functions in your package?

Thx!

**Comment by vonjd** [comment]
Thank you for the positive feedback, I really appreciate it!

`scorecard` seems to be an interesting package too, thank you for the heads up.

The philosophy of `woebin` is different: it gives the characteristics of the binning and doesn't do the binning itself whereas `optbin` does the binning (like e.g. `cut`).

The `OneR` function follows the same philosophy.

I built it this way because `OneR` is the main function and the others are just helper functions.
