### ISSUE TITLE
Understand and use rules given by OneR()

### ISSUE THREAD

**Issue by reena2018** [vonjd/OneR#9]
Can anyone tell me how to analyze n no of rules given by the  OneR() as an output.

**Comment by vonjd** [comment]
The question is unclear as it stands. According to the pic you sent me via LinkedIn you would only get as many rules as there are categories in your target variable (2 or 3 in your example) if you used OneR correctly. Those rules are then easily interpretable. I close this issue here and suggest that you open a new one where you provide a reproducible example.
